//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studyzy.LearnEnglishBySubtitle {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InnerDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InnerDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Studyzy.LearnEnglishBySubtitle.InnerDictionary", typeof(InnerDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the
        ///be
        ///to
        ///of
        ///and
        ///a
        ///in
        ///that
        ///have
        ///I
        ///it
        ///for
        ///not
        ///on
        ///with
        ///he
        ///as
        ///you
        ///do
        ///at
        ///this
        ///but
        ///his
        ///by
        ///from
        ///they
        ///we
        ///say
        ///her
        ///she
        ///or
        ///an
        ///will
        ///my
        ///one
        ///all
        ///would
        ///there
        ///their
        ///what
        ///so
        ///up
        ///out
        ///if
        ///about
        ///who
        ///get
        ///which
        ///go
        ///me
        ///when
        ///make
        ///can
        ///like
        ///time
        ///no
        ///just
        ///him
        ///know
        ///take
        ///people
        ///into
        ///year
        ///your
        ///good
        ///some
        ///could
        ///them
        ///see
        ///other
        ///than
        ///then
        ///now
        ///look
        ///only
        ///come
        ///its
        ///over
        ///think
        ///also
        ///back
        ///after
        ///use
        ///two
        ///how
        ///our
        ///work
        ///first
        ///well
        ///way
        ///even
        ///new
        ///want
        ///because
        ///any
        ///th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EasyWord {
            get {
                return ResourceManager.GetString("EasyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaron
        ///Abbott
        ///Abel
        ///Abigail
        ///Abner
        ///Abraham
        ///Ada
        ///Adair
        ///Adam
        ///Addison
        ///Adela
        ///Adelaide
        ///Adolph
        ///Adonis
        ///Adrian
        ///Afra
        ///Agatha
        ///Agnes
        ///Ahern
        ///Alan
        ///Albert
        ///Alberta
        ///Aldrich
        ///Alexander
        ///Alexia
        ///Alfred
        ///Alger
        ///Algernon
        ///Alice
        ///Allen
        ///Alma
        ///Alston
        ///Alva
        ///Alvin
        ///Alvis
        ///Amanda
        ///Amelia
        ///Amos
        ///Amy
        ///Anastasia
        ///Andre
        ///Andrea
        ///Andrew
        ///Andy
        ///Angela
        ///Angelo
        ///Ann
        ///Anna
        ///Annabelle
        ///Ansel
        ///Antoine
        ///Antonia
        ///Antonio
        ///Antony
        ///April
        ///Archer
        ///Archibald
        ///Aries
        ///Arlen
        ///Arlene
        ///Armand
        ///Armstrong
        ///Arno
        ///Arnold
        ///Arthur
        ///Arvin
        ///Asa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE UserVocabulary ( 
        ///    Id          INTEGER         PRIMARY KEY AUTOINCREMENT,
        ///    Word        VARCHAR( 200 )  NOT NULL    UNIQUE,
        ///    KnownStatus INT             NOT NULL,
        ///    CreateTime  DATETIME        NOT NULL,
        ///    UpdateTime  DATETIME        NOT NULL,
        ///    Source      VARCHAR( 50 ) 
        ///);
        ///CREATE TABLE Subtitle_KnownWord ( 
        ///    Id      INTEGER         PRIMARY KEY AUTOINCREMENT,
        ///    Word    VARCHAR( 200 )  NOT NULL,
        ///    AddTime DATETIME        NOT NULL 
        ///);
        ///CREATE TABLE Subtitle_NewWor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InitDb {
            get {
                return ResourceManager.GetString("InitDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aback,1
        ///abate,1
        ///abdomen,1
        ///abduct,1
        ///aberration,1
        ///abide,1
        ///abiding,1
        ///abject,1
        ///ablaze,1
        ///abnormal,1
        ///abnormality,1
        ///aboriginal,1
        ///abort,1
        ///abortive,1
        ///abound,1
        ///abrasive,1
        ///abreast,1
        ///absentee,1
        ///absorbing,1
        ///abstain,1
        ///abstinence,1
        ///abstraction,1
        ///abundance,1
        ///abundant,1
        ///abyss,1
        ///AC,1
        ///acceleration,1
        ///accelerator,1
        ///accentuate,1
        ///accolade,1
        ///accompaniment,1
        ///accomplice,1
        ///accomplishment,1
        ///accordance,1
        ///accordion,1
        ///accountancy,1
        ///accredit,1
        ///accrue,1
        ///accumulation,1
        ///accused,1
        ///accustom,1
        ///accustomed [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VocabularyRank {
            get {
                return ResourceManager.GetString("VocabularyRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to became,become
        ///began,begin
        ///bent,bend
        ///bit,bite
        ///bled,bleed
        ///blew,blow
        ///broke,break
        ///bred,breed
        ///brought,bring
        ///built,build
        ///bought,buy
        ///caught,catch
        ///chose,choose
        ///clung,cling
        ///came,come
        ///crept,creep
        ///dealt,deal
        ///dug,dig
        ///did,do
        ///drew,draw
        ///dreamed,dream
        ///drank,drink
        ///drove,drive
        ///ate,eat
        ///fell,fall
        ///fed,feed
        ///felt,feel
        ///fought,fight
        ///found,find
        ///fled,flee
        ///flew,fly
        ///forbade,forbid
        ///forgot,forget
        ///forgave,forgive
        ///froze,freeze
        ///got,get
        ///gave,give
        ///went,go
        ///grew,grow
        ///hung,hang
        ///had,have
        ///heard,hear
        ///hid,hi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WordOriginalMap {
            get {
                return ResourceManager.GetString("WordOriginalMap", resourceCulture);
            }
        }
    }
}
