//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studyzy.LearnEnglishBySubtitle {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InnerDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InnerDictionary() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Studyzy.LearnEnglishBySubtitle.InnerDictionary", typeof(InnerDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 a
        ///able
        ///about
        ///after
        ///all
        ///also
        ///am
        ///an
        ///and
        ///any
        ///are
        ///as
        ///ask
        ///at
        ///back
        ///bad
        ///be
        ///because
        ///been
        ///being
        ///best
        ///better
        ///big
        ///bike
        ///but
        ///by
        ///can
        ///case
        ///child
        ///come
        ///company
        ///could
        ///dad
        ///day
        ///did
        ///different
        ///do
        ///doing
        ///done
        ///drink
        ///early
        ///eat
        ///even
        ///eye
        ///fact
        ///feel
        ///few
        ///find
        ///first
        ///for
        ///from
        ///get
        ///give
        ///go
        ///god
        ///good
        ///got
        ///government
        ///great
        ///group
        ///had
        ///hand
        ///has
        ///have
        ///he
        ///hello
        ///her
        ///hey
        ///hi
        ///high
        ///him
        ///his
        ///how
        ///I
        ///if
        ///important
        ///in
        ///into
        ///is
        ///it
        ///its
        ///just
        ///keep
        ///know
        ///large
        ///last
        ///leave
        ///life
        ///like
        ///l [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string EasyWord {
            get {
                return ResourceManager.GetString("EasyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aaron
        ///Abbott
        ///Abel
        ///Abigail
        ///Abner
        ///Abraham
        ///Ada
        ///Adair
        ///Adam
        ///Addison
        ///Adela
        ///Adelaide
        ///Adolph
        ///Adonis
        ///Adrian
        ///Afra
        ///Agatha
        ///Agnes
        ///Ahern
        ///Alan
        ///Albert
        ///Alberta
        ///Aldrich
        ///Alexander
        ///Alexia
        ///Alfred
        ///Alger
        ///Algernon
        ///Alice
        ///Allen
        ///Alma
        ///Alston
        ///Alva
        ///Alvin
        ///Alvis
        ///Amanda
        ///Amelia
        ///Amos
        ///Amy
        ///Anastasia
        ///Andre
        ///Andrea
        ///Andrew
        ///Andy
        ///Angela
        ///Angelo
        ///Ann
        ///Anna
        ///Annabelle
        ///Ansel
        ///Antoine
        ///Antonia
        ///Antonio
        ///Antony
        ///April
        ///Archer
        ///Archibald
        ///Aries
        ///Arlen
        ///Arlene
        ///Armand
        ///Armstrong
        ///Arno
        ///Arnold
        ///Arthur
        ///Arvin
        ///Asa [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE TABLE UserVocabulary ( 
        ///    Id          INTEGER         PRIMARY KEY AUTOINCREMENT,
        ///    Word        VARCHAR( 200 )  NOT NULL
        ///                                UNIQUE,
        ///    KnownStatus INT             NOT NULL,
        ///    CreateTime  DATETIME        NOT NULL,
        ///    UpdateTime  DATETIME        NOT NULL,
        ///    Source      VARCHAR( 200 ),
        ///    Sentence    VARCHAR( 500 ),
        ///	IsStar      BOOLEAN         NOT NULL  
        ///);
        ///
        ///CREATE TABLE IgnoreWord ( 
        ///    Id         INTEGER         PRIMARY KEY AUTOINCREMENT,
        ///    Word [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string InitDb {
            get {
                return ResourceManager.GetString("InitDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 aback,1
        ///abate,1
        ///abdomen,1
        ///abduct,1
        ///aberration,1
        ///abide,1
        ///abiding,1
        ///abject,1
        ///ablaze,1
        ///abnormal,1
        ///abnormality,1
        ///aboriginal,1
        ///abort,1
        ///abortive,1
        ///abound,1
        ///abrasive,1
        ///abreast,1
        ///absentee,1
        ///absorbing,1
        ///abstain,1
        ///abstinence,1
        ///abstraction,1
        ///abundance,1
        ///abundant,1
        ///abyss,1
        ///AC,1
        ///acceleration,1
        ///accelerator,1
        ///accentuate,1
        ///accolade,1
        ///accompaniment,1
        ///accomplice,1
        ///accomplishment,1
        ///accordance,1
        ///accordion,1
        ///accountancy,1
        ///accredit,1
        ///accrue,1
        ///accumulation,1
        ///accused,1
        ///accustom,1
        ///accustomed [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string VocabularyRank {
            get {
                return ResourceManager.GetString("VocabularyRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 aardvarks	aardvark
        ///abas	aba
        ///abaci	abacus
        ///abacuses	abacus
        ///abalienates	abalienate
        ///abalienated	abalienate
        ///abalienating	abalienate
        ///abalones	abalone
        ///abandons	abandon
        ///abandoned	abandon
        ///abandoning	abandon
        ///abandonees	abandonee
        ///abandoners	abandoner
        ///abandonments	abandonment
        ///abases	abase
        ///abased	abase
        ///abasing	abase
        ///abasements	abasement
        ///abashes	abash
        ///abashed	abash
        ///abashing	abash
        ///abashments	abashment
        ///abates	abate
        ///abated	abate
        ///abating	abate
        ///abatements	abatement
        ///abatises	abatis
        ///abattoirs	abattoir [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string WordPrototype {
            get {
                return ResourceManager.GetString("WordPrototype", resourceCulture);
            }
        }
    }
}
